[sdl]
autolock=false
usescancodes=true

[dosbox]
machine=svga_s3
memsize=16
captures=capture

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[render]
frameskip=0
aspect=true
scaler=normal2x

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
oplmode=auto

[speaker]
pcspeaker=true
tandy=auto
disney=true

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[autoexec]
@echo off
mount c .
c:
set PATH=Z:\;C:\;C:\TC\BIN;C:\DAVE
set TEMP=C:\
prompt $P$G
call MENU.BAT
